// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALzX6wc_-GqKFL82UT2zJBV_49Zsb2HtM',
    appId: '1:412249606931:web:5ffedac89f4fba883528e6',
    messagingSenderId: '412249606931',
    projectId: 'test-65mybt',
    authDomain: 'test-65mybt.firebaseapp.com',
    storageBucket: 'test-65mybt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSU0Jm0TrTG3B349IAdQPHaiBKvlKnoyg',
    appId: '1:412249606931:android:bf249aa57ec9fb343528e6',
    messagingSenderId: '412249606931',
    projectId: 'test-65mybt',
    storageBucket: 'test-65mybt.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBafi7vW79sQdqp8lpQPhSt5025uMpzAeM',
    appId: '1:412249606931:web:21f2a044b28343733528e6',
    messagingSenderId: '412249606931',
    projectId: 'test-65mybt',
    authDomain: 'test-65mybt.firebaseapp.com',
    storageBucket: 'test-65mybt.appspot.com',
  );
}
